# Generated by Django 5.2.16 on 2026-08-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_alter_aicall_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicall',
            name='operation',
            field=models.CharField(choices=[('text', 'text'), ('json', 'json'), ('summarize', 'summarize'), ('grade', 'grade'), ('vision', 'vision'), ('ocr', 'ocr'), ('stt', 'stt')], max_length=20),
        ),
    ]
