# Generated by Django 5.2.16 on 2026-08-13 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='story_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='instrução da história'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='storytelling',
            field=models.BooleanField(default=False, verbose_name='personalizar marco com IA'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event',
            field=models.CharField(editable=False, max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Use apenas letras minúsculas, números, ponto, hífen ou underscore.', regex='^[a-z0-9]+(?:[._-][a-z0-9]+)*$')], verbose_name='evento'),
        ),
    ]
